### ISSUE TITLE
Clear dependencies array

### ISSUE THREAD

**Issue by inzerceubytovani** [ng2-ui/ng2-scrollable#1]
It's possible to clear dependencies array (like it is https://github.com/ng2-ui/ng2-auto-complete) and move all to devDependencies? To prevent download node_modules in production version.

**Comment by allenhwkim** [comment]
Thanks for reporting this. The work is done and published. Please verify and close this issue. A star for this repo would be appreciated if you like it. I am currently collecting stars :)
